name: Crates IO deployment release

on:
  push:
    tags:
      - "v*.*.*-release"

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo install cargo-tarpaulin
      - run: cargo tarpaulin --features json --out xml
      - uses: codecov/codecov-action@v4

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          components: clippy, rustfmt
          toolchain: stable
      - run: cargo fmt --check && cargo clippy --all-features --all-targets --workspace
      - run: cargo test --all-features --workspace

  push-to-crates-io:
    needs: [coverage, lint-and-test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Push release to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          export CARGO_REGISTRY_TOKEN="$CARGO_REGISTRY_TOKEN"
          cargo publish
