name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: sqlite://db.sqlite3

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install dependencies
      run: |
        apt update && apt install build-essential libsqlite3-dev curl -y
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

    - name: update cargo
      run: source "$HOME/.cargo/env" && rustup update

    - name: install diesel-cli and init db
      run: |
        source "$HOME/.cargo/env" && cargo install diesel_cli --no-default-features --features sqlite 
        diesel migration run

    - name: Build
      run: source "$HOME/.cargo/env" && cargo build --verbose

    - name: Run tests
      run: source "$HOME/.cargo/env" && cargo test --verbose -- --test-threads=1
